### ISSUE TITLE
panic: value is null

### ISSUE THREAD

**Issue by a0s** [jrhouston/tfk8s#16]
Hi! I am trying to convert https://github.com/prometheus-operator/prometheus-operator/blob/v0.46.0/bundle.yaml to hcl :

```shell
tfk8s --file bundle.yaml --output prometheus-operator_v0.46.0.tf --provider "kubernetes-alpha" --strip 
panic: value is null

goroutine 1 [running]:
github.com/zclconf/go-cty/cty.Value.LengthInt(0x13b5870, 0x1627bd8, 0x0, 0x0, 0xc000633c28)
        /Users/a0s/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1058 +0x28b
github.com/zclconf/go-cty/cty.Value.AsValueMap(0x13b5870, 0x1627bd8, 0x0, 0x0, 0xc000362600)
        /Users/a0s/go/pkg/mod/github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1315 +0x9d
main.yamlToHCL(0x13b5870, 0x1627bd8, 0x0, 0x0, 0x7ffeefbfeda4, 0x10, 0x1, 0x0, 0x13b5870, 0x1627bd8, ...)
        /Users/a0s/tfk8s/tfk8s.go:87 +0x6a
main.YAMLToTerraformResources(0x13b0ac0, 0xc0000107c0, 0x7ffeefbfeda4, 0x10, 0xc000010001, 0x0, 0x0, 0xc0000195fa, 0xc000186660)
        /Users/a0s/tfk8s/tfk8s.go:152 +0x2f0
main.main()
        /Users/a0s/tfk8s/tfk8s.go:194 +0x331
```

Seems it chashing  on empty parts:
```yaml
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
---

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  name: servicemonitors.monitoring.coreos.com
spec:
```
