### ISSUE TITLE
Hangs while converting custom resources

### ISSUE THREAD

**Issue by rumeshmadhusanka** [jrhouston/tfk8s#45]
Hangs while converting this.

```
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: nvidia-gpu-operator-group
  namespace: nvidia-gpu-operator
spec:
 targetNamespaces:
 - nvidia-gpu-operator
```

I installed tfk8s using go
