### ISSUE TITLE
Conversion of a k8s manifest with lines of string gives delimiter EOT with ,

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [jrhouston/tfk8s#50]
Consider the below sample k8s manifest:
```
apiVersion: v1
kind: Pod
metadata:
  name: tfk8s_error
spec:
  containers:
  - name: test
    image: golang
    command:
      - /bin/bash
    args:
      - -c
      - |
        echo "Hello"
```
The above file when converted to .tf using tfk8s, has a **","** after the second delimiter **`EOT`**
When `terraform apply` of the .tf file is attempted, we get the below error:

```
Acquiring state lock. This may take a few moments...
╷
│ Error: Unterminated template string
│
│   on ../modules/iks_res/cluster/simple-pod.tf line 28, in resource "kubernetes_manifest" "pod_tfk8s_error":
│   14:             echo "Hello"
│   15:
│   16:             EOT,
│   17:           ]
│   18:           "command" = [
│   19:             "/bin/bash",
│   20:           ]
│   21:           "image" = "golang"
│   22:           "name" = "test"
│   23:         },
│   24:       ]
│   25:     }
│   26:   }
│   27: }
│
│ No closing marker was found for the string.
```
