### ISSUE TITLE
Kustomize yaml manifeast crash

### ISSUE THREAD

**Issue by podishetty9966** [jrhouston/tfk8s#63]
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
patches:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: image-reflector-controller
      namespace: flux-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --aws-autologin-for-ecr
```

panic: value is null

goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x65
main.capturePanic()
        github.com/jrhouston/tfk8s/tfk8s.go:234 +0x39
panic({0x57a400, 0x5e60a8})
        runtime/panic.go:884 +0x212
github.com/zclconf/go-cty/cty.Value.LengthInt({{{0x0?, 0x0?}}, {0x0?, 0x0?}})
        github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1058 +0x27d
github.com/zclconf/go-cty/cty.Value.AsValueMap({{{0x0?, 0x0?}}, {0x0?, 0x0?}})
        github.com/zclconf/go-cty@v1.8.0/cty/value_ops.go:1315 +0x71
main.yamlToHCL({{{0x5e7768?, 0xc00016a940?}}, {0x5815a0?, 0xc00010bec0?}}, {0x0, 0x0}, 0x0, 0x0, 0x0?)
        github.com/jrhouston/tfk8s/tfk8s.go:111 +0x2bc
main.YAMLToTerraformResources({0x5e6b68?, 0xc0000146a0?}, {0x0, 0x0}, 0x0?, 0x0?, 0x0?)
        github.com/jrhouston/tfk8s/tfk8s.go:209 +0x2c8
main.main()
        github.com/jrhouston/tfk8s/tfk8s.go:267 +0x36d

⚠️  Oh no! Looks like your manifest caused tfk8s to crash.

Please open a GitHub issue and include your manifest YAML with the stack trace above,
or ping me on slack and I'll try and fix it!

GitHub: https://github.com/jrhouston/tfk8s/issues
Slack: #terraform-providers on https://kubernetes.slack.com

- Thanks, @jrhouston
